import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Nav from '../public/nav'
import Temp from '@/component/temp'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    {/* style jsx used only in same component  */}
  {/* ================================== */}
  <style jsx>
          {`
          .blog {
            background-color : yellow;
          }
          `}
        </style>
{/* ==================================== */}

<Temp/>


      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* <script src='/try.js    '></script> */}
      </Head>
      
      <Nav />
      {/* <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><li>Home</li></Link>
          <Link href='/blog'><li>Blog</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
          
        </ul>
      </nav> */}
      <main className={`${styles.main} ${inter.className}`}>
        {/* <div className={styles.description}> */}
          {/* the tmp is globaly imported from temp.js  */}
          <h1 className='hding tmp'>
            Hunting Coders
            </h1>
        
          
        {/* </div> */}

        <div className={styles.center}>
         <h2>
          Populer Blog
         </h2>

        </div>

        <div className="blog ">
          <div className="blogImage ">
            <h3>the blog content
            </h3>
            <h3 >the blog content
            </h3>
            <h3>the blog content
            </h3>
            <h3>the blog content
            </h3>
          </div>
        </div>
      </main>
    </>
  )
}
